### ISSUE TITLE
How to run the project?  What is the step1 and step2 in details? How to cite your work? 

### ISSUE THREAD

**Issue by guyucowboy** [kshannon/ucsd-dse-capstone#2]
Hi, kshannon
Thanks for sharing your great work!
How to run the project?  What is the step1 and step2 in details?
How to cite your work? Thanks for your help!
Best regards
Gu Yu

**Comment by kshannon** [comment]
HI @guyucowboy so sorry we missed this! This project was our master's thesi so I did not have any notifications set up for issues. Early December in a few weeks, I was going to come in and clean up somse of the instructions and add some more info. Running the code is one thing, to reproduce the results will take several weeks of multiple GPU training time using server grade GPUs. But that is for the 3d version, a 2d scaled down version should be easier to train. The other issue is that this was done on a very old version of tensorflow, I think the code will break on newer version (1.14/2.0). However, if you want to try and get it to work for those version you can always do a PR! 
Cheers, Kyle

We are finally getting around to writing up an arxiv.org paper, but for now feel free to cite it as:
```
Lung Nodule Classification and Localization
Suman Gunnala, Anil Luthra, Tony Reina, Kyle M Shannon
https://github.com/kshannon/lung-nodule-localization
2018
```
